
export const artworksData = {
  "1": {
    id: 1,
    title: "Trust Me ✨",
    description:
      "Dos personajes compartiendo un momento mágico de confianza mutua, representando la amistad y la complicidad.",
    image: "/images/trust-me.png",
    owner: "Ana María",
    created: "2025-03-15",
  },
  "2": {
    id: 2,
    title: "But Mom Says",
    description:
      "Un personaje elegante que nos recuerda que a veces lo que dice mamá es lo que importa, con un toque de humor.",
    image: "/images/mom-says.png",
    owner: "Ana María",
    created: "2025-03-16",
  },
  "3": {
    id: 3,
    title: "Historia",
    description:
      "Una reinterpretación de Bart Simpson con un mensaje profundo sobre la importancia de recordar nuestra historia.",
    image: "/images/bart-history.png",
    owner: "Ana María",
    created: "2025-03-17",
  },
  "4": {
    id: 4,
    title: "Mariposas ✨",
    description:
      "Una representación delicada de la belleza y la transformación, simbolizada por mariposas que rodean al personaje principal.",
    image: "/images/butterflies.png",
    owner: "Ana María",
    created: "2025-03-18",
  },
  "5": {
    id: 5,
    title: "Corazón",
    description:
      "Una interpretación de Shin Chan que explora el tema del amor y la amistad con el estilo característico de Ana María.",
    image: "/images/shin-chan.png",
    owner: "Ana María",
    created: "2025-03-19",
  },
  "6": {
    id: 6,
    title: "Empieza Ahora",
    description:
      "Un homenaje a Homer Simpson frente a la computadora, recordando que nunca es tarde para comenzar algo nuevo.",
    image: "/images/homer-computer.png",
    owner: "Ana María",
    created: "2025-03-20",
  },
  "7": {
    id: 7,
    title: "Skull ✨",
    description:
      "Una calavera estilizada que combina elementos de la cultura pop con un mensaje sobre la fugacidad de la vida.",
    image: "/images/skull.png",
    owner: "Ana María",
    created: "2025-03-21",
  },
  "8": {
    id: 8,
    title: "TV Off",
    description:
      "Lisa Simpson nos invita a apagar la televisión y explorar el mundo real, con un mensaje sobre la desconexión digital.",
    image: "/images/lisa-tv.png",
    owner: "Ana María",
    created: "2025-03-22",
  },
  "9": {
    id: 9,
    title: "Figura",
    description:
      "Una silueta enigmática que invita al espectador a completar la historia con su propia interpretación.",
    image: "/images/figure.png",
    owner: "Ana María",
    created: "2025-03-23",
  },
  "10": {
    id: 10,
    title: "Perrito ✨",
    description:
      "Un adorable perro con el estilo característico de Ana María, simbolizando la lealtad y la amistad incondicional.",
    image: "/images/dog.png",
    owner: "Ana María",
    created: "2025-03-24",
  },
  "11": {
    id: 11,
    title: "Hago que parezca fácil ✨",
    description:
      "Un personaje confiado montando skateboard con estilo, recordándonos que la verdadera maestría hace que lo difícil parezca sencillo.",
    image: "/images/skater-easy.png",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "12": {
    id: 12,
    title: "Bicho Raro",
    description: "Una criatura singular que celebra la individualidad y lo que nos hace únicos.",
    image: "/images/bichoraro.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "13": {
    id: 13,
    title: "Flores Vibrantes ✨",
    description: "Un estallido de color y vida, donde la naturaleza se encuentra con la imaginación.",
    image: "/images/floress.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "14": {
    id: 14,
    title: "El Pasado...✨",
    description: "Una reflexión melancólica sobre el tiempo y los recuerdos que dejamos atrás.",
    image: "/images/toitas.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "15": {
    id: 15,
    title: "Lisa 1",
    description: "Primera variación de un estudio de personaje icónico, explorando nuevas facetas.",
    image: "/images/lisa1.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "16": {
    id: 16,
    title: "Tan frio...",
    description: "Una atmósfera invernal que captura la belleza del silencio y la soledad.",
    image: "/images/toitas2.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "17": {
    id: 17,
    title: "Lisa 2 ✨",
    description: "Segunda interpretación vibrante, añadiendo elementos mágicos al diseño original.",
    image: "/images/lisa2.jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "18": {
    id: 18,
    title: "Asuntos del Corazón",
    description: "Una obra emotiva que profundiza en las complejidades de los sentimientos humanos.",
    image: "/images/Nuevo (1).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "19": {
    id: 19,
    title: "¿Gesto de amor?✨",
    description: "Cuestionando las formas en que expresamos afecto en un mundo moderno.",
    image: "/images/Nuevo (3).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "20": {
    id: 20,
    title: "Aferrarse",
    description: "La lucha por mantener lo que amamos, representada con fuerza visual.",
    image: "/images/Nuevo (4).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "21": {
    id: 21,
    title: "Libertad ✨",
    description: "Un grito visual de independencia y la alegría de romper cadenas.",
    image: "/images/Nuevo (5).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "22": {
    id: 22,
    title: "Crisis Previa",
    description: "Capturando el momento de tensión antes del cambio, lleno de energía contenida.",
    image: "/images/Nuevo (6).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "23": {
    id: 23,
    title: "Asuntos✨",
    description: "Una composición abstracta que invita a reflexionar sobre lo cotidiano.",
    image: "/images/Nuevo (7).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "24": {
    id: 24,
    title: "Gesto de Amor ✨",
    description: "La simplicidad y pureza de un acto de amor verdadero.",
    image: "/images/Nuevo (8).jpg",
    owner: "Ana María",
    created: "2025-04-01",
  },
  "25": {
    id: 25,
    title: "Nueva Perspectiva",
    description: "Una obra vibrante que invita a mirar el mundo desde un ángulo diferente.",
    image: "/images/Nuevox (1).jpeg",
    owner: "Ana María",
    created: "2025-04-02",
  },
  "26": {
    id: 26,
    title: "Horizontes",
    description: "Exploración de nuevos horizontes artísticos con una paleta de colores audaz.",
    image: "/images/Nuevox (2).jpeg",
    owner: "Ana María",
    created: "2025-04-03",
  },
  "27": {
    id: 27,
    title: "Reflejos Urbanos",
    description: "Interpretación contemporánea de la vida urbana y sus múltiples reflejos.",
    image: "/images/Nuevox (3).jpeg",
    owner: "Ana María",
    created: "2025-04-04",
  },
  "28": {
    id: 28,
    title: "Instante Fugaz",
    description: "Capturando la belleza de un momento efímero con trazos dinámicos.",
    image: "/images/Nuevox (4).jpeg",
    owner: "Ana María",
    created: "2025-04-05",
  },
  "29": {
    id: 29,
    title: "Memorias",
    description: "Una evocación visual de recuerdos y nostalgia con un toque moderno.",
    image: "/images/Nuevox (5).jpeg",
    owner: "Ana María",
    created: "2025-04-06",
  },
  "30": {
    id: 30,
    title: "Ecos del Ayer",
    description: "Resonancias del pasado reinterpretadas en un lenguaje visual actual.",
    image: "/images/Nuevox (6).jpeg",
    owner: "Ana María",
    created: "2025-04-07",
  },
  "31": {
    id: 31,
    title: "Sueños Lúcidos",
    description: "Un viaje onírico a través de formas y colores que desafían la realidad.",
    image: "/images/Nuevox (7).jpeg",
    owner: "Ana María",
    created: "2025-04-08",
  },
  "32": {
    id: 32,
    title: "Fragmentos",
    description: "La belleza de lo incompleto y la reconstrucción de la identidad.",
    image: "/images/Nuevox (8).jpeg",
    owner: "Ana María",
    created: "2025-04-09",
  },
  "33": {
    id: 33,
    title: "Silencios",
    description: "El poder de lo que no se dice, expresado a través de la imagen.",
    image: "/images/Nuevox (9).jpeg",
    owner: "Ana María",
    created: "2025-04-10",
  },
  "34": {
    id: 34,
    title: "Mirada Interior",
    description: "Una introspección profunda visualizada con sensibilidad artística.",
    image: "/images/Nuevox (10).jpeg",
    owner: "Ana María",
    created: "2025-04-11",
  },
  "35": {
    id: 35,
    title: "Caminos Cruzados",
    description: "La intersección de destinos y posibilidades en una composición compleja.",
    image: "/images/Nuevox (11).jpeg",
    owner: "Ana María",
    created: "2025-04-12",
  },
  "36": {
    id: 36,
    title: "Destellos",
    description: "Pequeñas luces de esperanza y creatividad en medio del caos.",
    image: "/images/Nuevox (12).jpeg",
    owner: "Ana María",
    created: "2025-04-13",
  },
  "37": {
    id: 37,
    title: "Esencia Pura ✨",
    description: "La manifestación más auténtica del estilo y la visión de la artista.",
    image: "/images/Nuevox (13).jpeg",
    owner: "Ana María",
    created: "2025-04-14",
  },
} as const;

export type Artwork = typeof artworksData[keyof typeof artworksData];

export const artworksArray = Object.values(artworksData);
